#version 430 core

layout( local_size_x = 1, local_size_y = 1, local_size_z = 1 ) in;

uniform ivec2 size;
uniform ivec2 offset;
uniform float k;

restrict buffer buf0 {
    vec2 data[];
};

restrict readonly buffer buf1 {
    vec2 delta[];
};

restrict readonly buffer buf2 {
    int mask[];
};

void main() {
    ivec2 xy = ivec2(gl_GlobalInvocationID.xy) + offset;
    int index = xy.y * size.x + xy.x;
    if(mask[index] == 0) {
        data[index] = data[index] + k * delta[index];
    }
}
